"""initial meta schema — all tables from meta_ads.db.models

Revision ID: 0001_initial_meta_schema
Revises:
Create Date: 2026-07-01

Creates every table in the `meta` schema straight from the SQLAlchemy metadata,
so this migration is always in sync with models.py. Later migrations should be
hand-written / autogenerated deltas.

Prereq (one-time, superuser): CREATE SCHEMA meta AUTHORIZATION fb_svc;
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from meta_ads.db.models import Base

revision: str = "0001_initial_meta_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
